name: 'Dependency Review'
on: [pull_request]

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - uses: dsp-testing/fluffy-engine@main
        with:
          repo_token: {{ secrets.REPO_TOKEN }}
